times = ('Botafogo', 'Palmeiras', 'Cruzeiro', 'Fortaleza', 'São Paulo', 'Fluminense', 'Grêmio', 'Internacional', 'Bahia', 'Atletico-PR',
         'Vasco', 'Bragantino', 'Cuiaba', 'Santos', 'Corinthians', 'Atletico-MG', 'Flamengo', 'Goias', 'Coritiba', 'America-MG')
print('-=' * 25)
print(f'Times que disputam Brasileirão 2023: {times}')
print('-=' * 25)
print(f'Os cinco primeiros times do Brasileirão são: {times[:5]}')
print('-=' * 25)
print(f'Os quatro ultimos do Brasileirão são: {times[16:]}')
print('-=' * 25)
print(f'Times organizados em ordem alfabética: {sorted(times)}')
print('-=' * 25)
print('O time Atlético-MG esta na {}° posição'.format(times.index('Atletico-MG')+1))
print(f'O time Atlético-MG está na {times.index("Atletico-MG")+1}° posição')
print('-=' * 25)